# Generated by Django 3.1.7 on 2021-03-10 04:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shuttles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shuttle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('destination', models.CharField(blank=True, max_length=255, verbose_name='Shuttle Destination')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
