# Generated by Django 3.1.7 on 2021-04-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttles', '0002_auto_20210309_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shuttle',
            name='destination',
        ),
        migrations.AddField(
            model_name='shuttle',
            name='campus_depart_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Campus Departure Location'),
        ),
        migrations.AddField(
            model_name='shuttle',
            name='campus_depart_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Campus Departure Time'),
        ),
        migrations.AddField(
            model_name='shuttle',
            name='dropoff_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shuttle Dropoff Location'),
        ),
        migrations.AddField(
            model_name='shuttle',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shuttle Pickup Location'),
        ),
        migrations.AddField(
            model_name='shuttle',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pickup Time'),
        ),
    ]
