# Generated by Django 3.1.7 on 2021-04-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttles', '0003_auto_20210411_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuttle',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Return Time'),
        ),
    ]
