# Generated by Django 3.1.7 on 2021-04-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttles', '0004_shuttle_return_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuttle',
            name='time_slot',
            field=models.CharField(choices=[('fri_7_9', 'Friday, 7:00-9:00'), ('sat_1130_130', 'Saturday, 11:30-1:30'), ('sat_2_4', 'Saturday, 2:00-4:00'), ('sat_7_9', 'Saturday, 7:00-9:00')], default='fri_7_9', max_length=200),
        ),
    ]
