# Generated by Django 3.1.7 on 2021-04-12 00:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shuttles', '0007_auto_20210412_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuttle',
            name='open_seats',
            field=models.IntegerField(blank=True, default=9, verbose_name='Open Seats'),
        ),
        migrations.AddField(
            model_name='shuttle',
            name='passengers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
