# Generated by Django 3.1.7 on 2021-04-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttles', '0010_shuttle_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shuttle',
            name='dropoff_location',
        ),
        migrations.AddField(
            model_name='shuttle',
            name='destinatation',
            field=models.CharField(blank=True, choices=[('San Ramon Safeway', 'San Ramon Safeway'), ("San Ramon Trader Joe's", "San Ramon Trader Joe's"), ("Danville Trader Joe's", "Danville Trader Joe's"), ('San Ramon Sharetea', 'San Ramon Sharetea')], max_length=255, null=True, verbose_name='Shuttle Dropoff Location'),
        ),
    ]
