# Generated by Django 3.1.7 on 2021-04-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuttles', '0011_auto_20210412_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shuttle',
            old_name='destinatation',
            new_name='destination',
        ),
    ]
