# Generated by Django 3.1.7 on 2021-04-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttles', '0014_auto_20210412_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttle',
            name='time_slot',
            field=models.CharField(choices=[('Friday 7:00-9:00 p.m.', 'Friday 7:00-9:00 p.m.'), ('Saturday 11:30-1:30 p.m.', 'Saturday 11:30-1:30 p.m.'), ('Saturday 2:00-4:00', 'Saturday 2:00-4:00'), ('Saturday 7:00-9:00', 'Saturday 7:00-9:00')], max_length=200, verbose_name='Time Slot'),
        ),
    ]
