# Generated by Django 3.1.7 on 2021-04-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttles', '0016_auto_20210413_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttle',
            name='time_slot',
            field=models.IntegerField(choices=[(0, 'Friday 7:00-9:00'), (1, 'Saturday 11:30-1:30'), (2, 'Saturday 2:00-4:00'), (3, 'Saturday 7:00-9:00')], verbose_name='Time Slot'),
        ),
    ]
