# Generated by Django 3.1.7 on 2021-04-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttles', '0019_auto_20210413_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shuttle',
            name='uid',
        ),
        migrations.AddField(
            model_name='shuttle',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending Approval', 'Pending Approval'), ('Approved', 'Approved')], default='Pending Approval', max_length=255, verbose_name='Status'),
        ),
    ]
