# Generated by Django 3.1.7 on 2021-04-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttles', '0020_auto_20210413_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttle',
            name='status',
            field=models.CharField(blank=True, choices=[('Requested', 'Requested'), ('Approved', 'Approved')], default='Pending Approval', max_length=255, verbose_name='Status'),
        ),
    ]
