# Generated by Django 3.1.7 on 2021-04-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttles', '0022_auto_20210413_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttle',
            name='destination',
            field=models.CharField(choices=[('San Ramon Safeway/Sharetea', 'San Ramon Safeway/Sharetea'), ("San Ramon Trader Joe's", "San Ramon Trader Joe's"), ("Danville Trader Joe's", "Danville Trader Joe's"), ('Dublin 99 Ranch Market', 'Dublin 99 Ranch Market'), ('San Ramon T4', 'San Ramon T4')], max_length=255, verbose_name='Destination'),
        ),
    ]
