# Generated by Django 3.1.7 on 2021-04-16 02:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shuttles', '0023_auto_20210416_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttle',
            name='passengers',
            field=models.ManyToManyField(limit_choices_to={'is_test_user': False}, to=settings.AUTH_USER_MODEL),
        ),
    ]
