# Generated by Django 3.1.7 on 2021-04-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttles', '0024_auto_20210416_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttle',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Launched', 'Launched'), ('Landed', 'Landed'), ('Archived', 'Archived'), ('Deleted', 'Deleted')], default='Pending', max_length=255, verbose_name='Status'),
        ),
    ]
