# Generated by Django 3.1.7 on 2021-04-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shuttle_tokens',
            field=models.IntegerField(blank=True, default=0, verbose_name='Shuttle Tokens'),
        ),
    ]
