# Generated by Django 3.1.7 on 2021-04-12 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_shuttle_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shuttle_tokens',
        ),
    ]
