# Generated by Django 3.1.7 on 2021-04-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210416_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_test_user',
            field=models.BooleanField(blank=True, default=False, verbose_name='Test User'),
        ),
    ]
