# Generated by Django 3.1.7 on 2021-04-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=300)),
                ('min_passengers_for_request', models.IntegerField(default=3)),
                ('max_reservations_per_user', models.IntegerField(default=2)),
            ],
        ),
    ]
