# Generated by Django 3.1.7 on 2021-04-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_auto_20210413_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controls',
            name='max_reservations_per_user',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=2, verbose_name='Max. Active Reservations per Student'),
        ),
        migrations.AlterField(
            model_name='controls',
            name='min_passengers_for_request',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=3, verbose_name='Min. Passengers to Request Shuttle'),
        ),
        migrations.AlterField(
            model_name='controls',
            name='name',
            field=models.CharField(default='default', max_length=300, verbose_name='Name'),
        ),
    ]
